### ISSUE TITLE
Outtömlig Kärra med Malm inte helt översatt

### ISSUE THREAD

**Issue by XCOM-HUB** [CalZing/HeroesIIISwedish#10]
- Jag använder mig av eran Mod via VCMI 1.5.7 på en Windows 11 Pro dator (version 24H2)

![Outtömlig Kärra med Malm](https://github.com/user-attachments/assets/05394db4-4064-4306-abe1-59162b83646d)

**Comment by CalZing** [comment]
ArtEvents.txt är inte helt översatt enligt statusen, så detta är förväntat. Du kommer att få dessa meddelanden på majoriteten, om inte alla, artefakter.

**Comment by XCOM-HUB** [comment]
Okej. Jag håller på att lära mig hur man redigerar här i GitHub. Wish me luck!
