### ISSUE TITLE
Vägfararens Ring är inte helt översatt

### ISSUE THREAD

**Issue by XCOM-HUB** [CalZing/HeroesIIISwedish#9]
- Jag använder mig av eran Mod via VCMI 1.5.7 på en Windows 11 Pro dator (version 24H2)

![Vägfararens Ring](https://github.com/user-attachments/assets/aafcf885-014e-4796-897a-006154f42cdf)

**Comment by CalZing** [comment]
Detta är förväntat. Vi blev typ 90% klara och inte korrekturlästa. En av filerna som vi inte översatte var den med alla småberättelse om hur man fick spelets alla 140+ artefakter. Artefaktöversättningen kommer från annat håll, så det ser lite tokigt ut

**Comment by XCOM-HUB** [comment]
Uppfattat 👍
